/**
 * PHASE 4 — PARSER IMPLEMENTATION §1.5 & §4.4 Step 3
 * KPI Block Extraction from SeamlessHR Appraisal Text
 */

import { KpiRecord, PerspectiveRecord, SourceRef } from './types.js';
import { normalizeNumber, normalizeTimestamp } from './normalize.js';
import { inferKpiType } from './inferKpiType.js';
import { buildKpiRecord } from '../schema/builder.js';

export interface ExtractedKpiRaw {
    title: string;
    objective_prose: string;
    type_string: string | null;
    completion_percent: number | null;
    target: number | null;
    actual: number | null;
    actual_score: number | null;
    weight: number | null;
    weighted_score: number | null;
    final_score: number | null;
    reviewer_target: number | null;
    reviewer_actual: number | null;
    employee_target: number | null;
    employee_actual: number | null;
    comment: string | null;
    comment_author: string | null;
    comment_author_department: string | null;
    comment_timestamp: string | null;
}

export function extractKpiBlock(blockText: string): ExtractedKpiRaw {
    // 1. Extract Type N verbatim
    const typeMatch = blockText.match(/Type\s+(\d+)/i);
    const type_string = typeMatch ? `Type ${typeMatch[1]}` : null;

    // 2. Extract completion percent
    const compMatch = blockText.match(/(\d+)%\s+Complete/i);
    const completion_percent = compMatch ? parseInt(compMatch[1]!, 10) : null;

    // 3. Extract "Target X Actual Y Actual Score Z"
    const table1 = blockText.match(/Target\s+([\d,.]+)\s+Actual\s+([\d,.]+)(?:\s+Actual\s+Score\s+([\d,.]+))?/i);
    const target = table1 ? normalizeNumber(table1[1]) : null;
    const actual = table1 ? normalizeNumber(table1[2]) : null;
    const actual_score = table1 && table1[3] ? normalizeNumber(table1[3]) : null;

    // 4. Extract "Weight W Weighted Score WS Final Score FS"
    const table2 = blockText.match(/Weight\s+([\d,.]+)\s+Weighted\s+Score\s+([\d,.]+)\s+Final\s+Score\s+([\d,.]+)/i);
    const weight = table2 ? normalizeNumber(table2[1]) : null;
    const weighted_score = table2 ? normalizeNumber(table2[2]) : null;
    const final_score = table2 ? normalizeNumber(table2[3]) : null;

    // 5. Extract "Reviewer Target X Actual Y Employee Target Z Actual W"
    const table3 = blockText.match(/Reviewer\s+Target\s+([\d,.]+)\s+Actual\s+([\d,.]+)\s+Employee\s+Target\s+([\d,.]+)\s+Actual\s+([\d,.]+)/i);
    const reviewer_target = table3 ? normalizeNumber(table3[1]) : null;
    const reviewer_actual = table3 ? normalizeNumber(table3[2]) : null;
    const employee_target = table3 ? normalizeNumber(table3[3]) : null;
    const employee_actual = table3 ? normalizeNumber(table3[4]) : null;

    // 6. Extract comment and author
    const commentMatch = blockText.match(/COMMENT\(S\)\s+FOR\s+KPI\s+([\s\S]+?)(?=\n\s*(?:[A-Z][a-z]+|\d+(?:st|nd|rd|th)|##|SIGNATURES)|$)/i);
    const comment = commentMatch ? commentMatch[1]!.trim() : null;

    const lines = blockText.split('\n').map(l => l.trim()).filter(l => l.length > 0);
    let comment_author: string | null = null;
    let comment_author_department: string | null = null;

    if (comment) {
        const commentPreview = comment.slice(0, 20);
        const commentIdx = lines.findIndex(l => l.includes(commentPreview));
        if (commentIdx >= 0 && commentIdx + 2 < lines.length) {
            comment_author = lines[commentIdx + 1] ?? null;
            comment_author_department = lines[commentIdx + 2] ?? null;
        }
    }

    // 7. Extract timestamp
    const tsMatch = blockText.match(/(\d+)(?:st|nd|rd|th)?\s+([A-Za-z]+),?\s+(\d{4})[.,\s]+(\d{1,2}):(\d{2})\s*(AM|PM)?/i);
    const comment_timestamp = tsMatch ? normalizeTimestamp(tsMatch) : null;

    // 8. Extract objective prose (text before the first table)
    const firstTableIdx = blockText.search(/Entire\s+Cycle|Target\s+[\d,.]+/i);
    let rawProse = firstTableIdx > 0 ? blockText.slice(0, firstTableIdx).trim() : blockText.slice(0, 100).trim();

    const weightMatch = rawProse.match(/Weight\s+of\s+Perspective:\s*[\d,.]+/i);
    if (weightMatch && weightMatch.index !== undefined) {
        rawProse = rawProse.slice(weightMatch.index + weightMatch[0].length).trim();
    }

    // The first non-header line is the title, remaining lines the objective prose
    const proseLines = rawProse
        .split('\n')
        .map(l => l.trim())
        .filter(l => l.length > 0 && !l.startsWith('##') && !/^Weight of Perspective/i.test(l) && !/^APPRAISAL PERIOD/i.test(l) && !/^(?:Employee|Staff)\s+Name/i.test(l) && !/^Generated by/i.test(l) && !/Royal Crown/i.test(l));
    const title = proseLines[0] ?? 'Objective';
    const objective_prose = proseLines.join(' ');

    return {
        title,
        objective_prose,
        type_string,
        completion_percent,
        target,
        actual,
        actual_score,
        weight,
        weighted_score,
        final_score,
        reviewer_target,
        reviewer_actual,
        employee_target,
        employee_actual,
        comment,
        comment_author,
        comment_author_department,
        comment_timestamp,
    };
}

export function buildKpiFromExtracted(
    raw: ExtractedKpiRaw,
    kpiIndex: number,
    currentPerspective: PerspectiveRecord | null,
    filename: string,
    page: number
): KpiRecord {
    const code = `KPI-${String(kpiIndex + 1).padStart(2, '0')}`;
    const inferredType = inferKpiType(raw.title, raw.objective_prose);

    const source: SourceRef = {
        document: filename,
        page,
        row: kpiIndex + 1,
        field: 'kpi_block',
    };

    return buildKpiRecord({
        code,
        title: raw.title,
        objective_text: raw.objective_prose,
        kpi_type_from_pdf: raw.type_string,
        kpi_type_inferred: inferredType,
        target: raw.target,
        actual: raw.actual,
        actual_score_from_pdf: raw.actual_score,
        weight: raw.weight,
        weighted_score_from_pdf: raw.weighted_score,
        final_score_from_pdf: raw.final_score,
        completion_percent: raw.completion_percent,
        bsc_perspective: currentPerspective?.name ?? 'financial',
        perspective_weight: currentPerspective?.weight ?? null,
        reviewer_target: raw.reviewer_target,
        reviewer_actual: raw.reviewer_actual,
        employee_target: raw.employee_target,
        employee_actual: raw.employee_actual,
        comment: raw.comment,
        comment_author: raw.comment_author,
        comment_author_department: raw.comment_author_department,
        comment_timestamp: raw.comment_timestamp,
        source,
    });
}
