/**
 * PHASE 4 — PARSER IMPLEMENTATION §4.4 Step 1
 * SeamlessHR PDF Template Fingerprint Detection
 */

export interface FingerprintResult {
    isSeamlessHR: boolean;
    signals: string[];
}

export function fingerprint(text: string): FingerprintResult {
    const signals: string[] = [];

    // Signal 1: Footer
    if (/Generated by SeamlessHR\.com/i.test(text)) {
        signals.push('footer');
    }

    // Signal 2: Company header
    if (/Royal Crown Packaging Company Limited/i.test(text)) {
        signals.push('company');
    }

    // Signal 3: Period line pattern (e.g. 1st January, 2026 - 31st May, 2026)
    if (/\d+(?:st|nd|rd|th)?\s+[A-Za-z]+,?\s+\d{4}\s*-\s*\d+(?:st|nd|rd|th)?\s+[A-Za-z]+,?\s+\d{4}/i.test(text)) {
        signals.push('period');
    }

    // Signal 4: Structure header
    if (/\d+\s+Perspective\s+\d+\s+Objectives/i.test(text)) {
        signals.push('structure');
    }

    // Signal 5: Entire Cycle Type N pattern
    if (/Entire Cycle\s+Type\s+\d+/i.test(text)) {
        signals.push('kpi_table');
    }

    // Signal 6: Signatures header
    if (/SIGNATURES/i.test(text)) {
        signals.push('signatures');
    }

    return {
        // PDF is a SeamlessHR appraisal if ANY TWO signals match
        isSeamlessHR: signals.length >= 2,
        signals,
    };
}
