/**
 * REAL SEAMLESSHR MULTI-PAGE STREAM PARSER
 *
 * Implements the battle-tested extraction engine for real Pinnacle Group/RCPL
 * SeamlessHR appraisal PDFs.
 *
 * Handles:
 *  - Vertically stacked fields ("Target\n100\nActual\n100...")
 *  - Letter-spaced cover-page headers ("E M P L O Y E E I D", "J O B R O L E")
 *  - Repeated per-page footer boilerplate stripping
 *  - Page-offset tracking across page boundaries
 *  - Full 8-type taxonomy mapping from "Type N"
 *  - Lead-clause KPI type inference
 *  - Appraisal-level comments with timestamp, role, department, and text
 *  - Multi-signatory extraction (Reviewer, Counter Signing, ARC)
 */

import { KpiType } from './types.js';

export interface SeamlessHrSignatory {
    name: string;
    department: string | null;
    signed_at: string | null;
}

export interface SeamlessHrComment {
    author_name: string;
    author_role: string;
    department: string | null;
    commented_at: string | null;
    text: string | null;
}

export interface SeamlessHrPerspectiveRaw {
    name: string;
    weight: number | null;
    source_page: number;
}

export interface SeamlessHrKpiRaw {
    code: string;
    perspective: string | null;
    objective: string;
    entire_cycle_type: number | null;
    completion_percent: number | null;
    target: number | null;
    actual: number | null;
    actual_score: number | null;
    weight: number | null;
    weighted_score: number | null;
    final_score_from_pdf: number | null;
    reviewer_target: number | null;
    reviewer_actual: number | null;
    employee_target: number | null;
    employee_actual: number | null;
    self_vs_supervisor_delta: number | null;
    source_page: number;
    kpi_type_from_pdf: KpiType | null;
    kpi_type_inferred: KpiType;
    kpi_type: KpiType;
    kpi_type_divergence: boolean;
}

export interface SeamlessHrCoverFields {
    employee_name: string;
    employee_id_from_pdf: string | null;
    job_title: string | null;
    department: string | null;
    branch: string | null;
    gender: string | null;
    time_in_company: string | null;
    final_score_from_pdf: number | null;
    rating_from_pdf: string | null;
    recommendation_from_pdf: string | null;
    nine_box_position_from_pdf: string | null;
}

export interface SeamlessHrParsedAppraisal {
    cover: SeamlessHrCoverFields;
    cycle_label: string | null;
    cycle_period_start: string | null;
    cycle_period_end: string | null;
    review_period_start: string | null;
    review_period_end: string | null;
    is_test_phase: boolean;
    perspectives: SeamlessHrPerspectiveRaw[];
    kpis: SeamlessHrKpiRaw[];
    comments: SeamlessHrComment[];
    reviewer: SeamlessHrSignatory | null;
    counter_signer: SeamlessHrSignatory | null;
    arc: SeamlessHrSignatory | null;
    line_manager_recommendation: string | null;
    arc_recommendation: string | null;
}

const SOURCE_TYPE_CODE_MAP: Record<number, KpiType> = {
    1: 'TYPE_1_HIGHER_BETTER',
    2: 'TYPE_2_LESS_MEANS_MORE',
    3: 'TYPE_3_LESS_OR_NOTHING',
    4: 'TYPE_4_ALL_OR_NOTHING',
    5: 'TYPE_5_NEGATIVE_SCORING',
    6: 'TYPE_6_THRESHOLD',
    7: 'TYPE_7_LOWER_THRESHOLD',
    8: 'TYPE_8_RATING_SCALE',
};

const FOOTER_RE = /Royal Crown Packaging Company Limited\.?\s*Generated by SeamlessHR\.com/i;

const BOILERPLATE_RE =
    /Appraisal Report\s*:\s*[^\n]*\n?|\d{4}\s*Royal Crown Packaging Company Limited\.?\s*Generated by SeamlessHR\.com\.?\n?/gi;

export function stripBoilerplate(page: string): string {
    return page.replace(BOILERPLATE_RE, '');
}

function escapeRegExp(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function spacedLabelPattern(label: string): RegExp {
    const body = label
        .split('')
        .map((ch) => {
            if (ch === ' ') return '\\s+';
            if (ch === '-') return '-?\\s*';
            return `${escapeRegExp(ch)}\\s*`;
        })
        .join('');
    return new RegExp(body, 'i');
}

const COVER_LABELS = [
    'EMPLOYEE ID',
    'DEPARTMENT',
    'JOB ROLE',
    'TIME IN COMPANY',
    'BRANCH',
    'GENDER',
    '9-BOX MATRIX POSITION',
] as const;

interface LabelHit {
    label: string;
    start: number;
    end: number;
}

function findCoverLabelHits(page1: string): LabelHit[] {
    const hits: LabelHit[] = [];
    for (const label of COVER_LABELS) {
        const m = spacedLabelPattern(label).exec(page1);
        if (m) hits.push({ label, start: m.index, end: m.index + m[0].length });
    }
    hits.sort((a, b) => a.start - b.start);
    return hits;
}

function cleanValue(raw: string): string {
    return raw.replace(/\s+/g, ' ').trim();
}

const MONTHS: Record<string, number> = {
    january: 1, february: 2, march: 3, april: 4, may: 5, june: 6,
    july: 7, august: 8, september: 9, october: 10, november: 11, december: 12,
};

export function parseLooseDate(raw: string): string | null {
    const m = /(\d{1,2})\w*\s+([A-Za-z]+),?\s+(\d{4})/.exec(raw);
    if (!m) return null;
    const day = parseInt(m[1]!, 10);
    const month = MONTHS[m[2]!.toLowerCase()];
    const year = parseInt(m[3]!, 10);
    if (!month || day < 1 || day > 31) return null;
    return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

export function parseLooseTimestamp(raw: string): string | null {
    const datePart = parseLooseDate(raw);
    if (!datePart) return null;
    const timeMatch = /(\d{1,2}:\d{2}\s*[AP]M)/i.exec(raw);
    return timeMatch ? `${datePart} ${timeMatch[1]!.toUpperCase()}` : datePart;
}

export function extractCoverFields(page1: string): SeamlessHrCoverFields {
    const lines = page1.split('\n').map((l) => l.trim()).filter(Boolean);
    let employee_name = '';
    const explicitNameM = /(?:Employee\s+Name|Staff\s+Name|Name):\s*([^\n\r,]+)/i.exec(page1);
    if (explicitNameM) {
        employee_name = explicitNameM[1]!.trim();
    } else {
        const candidate = lines.find(l => !/Royal Crown|SeamlessHR|Appraisal|Report|Page|^\d+/i.test(l));
        employee_name = candidate ?? lines[0] ?? '';
    }

    const finalScoreM = /FINAL SCORE:\s*(\d+(?:\.\d+)?)%/i.exec(page1);
    const ratingM = /Rating:\s*([^\n]+)/i.exec(page1);
    const recommendationM = /Recommendation:\s*([^\n]+)/i.exec(page1);

    const hits = findCoverLabelHits(page1);
    const values: Record<string, string> = {};
    for (let i = 0; i < hits.length; i++) {
        const hit = hits[i]!;
        const next = hits[i + 1];
        const sliceEnd = next ? next.start : page1.indexOf('Appraisal Report', hit.end);
        const raw = page1.slice(hit.end, sliceEnd < 0 ? page1.length : sliceEnd);
        values[hit.label] = cleanValue(raw);
    }

    return {
        employee_name,
        employee_id_from_pdf: values['EMPLOYEE ID'] ?? null,
        job_title: values['JOB ROLE'] ?? null,
        department: values['DEPARTMENT'] ?? null,
        branch: values['BRANCH'] ?? null,
        gender: values['GENDER'] ?? null,
        time_in_company: values['TIME IN COMPANY'] ?? null,
        final_score_from_pdf: finalScoreM ? parseFloat(finalScoreM[1]!) : null,
        rating_from_pdf: ratingM ? ratingM[1]!.trim() : null,
        recommendation_from_pdf: recommendationM ? recommendationM[1]!.trim() : null,
        nine_box_position_from_pdf: values['9-BOX MATRIX POSITION'] ?? null,
    };
}

const DATE_RANGE = `(\\d{1,2}\\w{0,2}\\s+[A-Za-z]+,?\\s*\\d{4}\\.?)\\s*-\\s*(\\d{1,2}\\w{0,2}\\s+[A-Za-z]+,?\\s*\\d{4}\\.?)`;

export function extractPeriodFields(fullText: string): {
    cycle_label: string | null;
    cycle_period_start: string | null;
    cycle_period_end: string | null;
    review_period_start: string | null;
    review_period_end: string | null;
    is_test_phase: boolean;
} {
    const cycleM = new RegExp(`${DATE_RANGE}\\s*APPRAISAL\\s+CYCLE`, 'i').exec(fullText);
    const periodM = new RegExp(`${DATE_RANGE}\\s*APPRAISAL\\s+PERIOD`, 'i').exec(fullText);
    const labelM = /APPRAISAL CYCLE\s*\n?\s*([^\n]+)/i.exec(fullText);

    return {
        cycle_label: labelM ? labelM[1]!.trim() : null,
        cycle_period_start: cycleM ? parseLooseDate(cycleM[1]!) : null,
        cycle_period_end: cycleM ? parseLooseDate(cycleM[2]!) : null,
        review_period_start: periodM ? parseLooseDate(periodM[1]!) : null,
        review_period_end: periodM ? parseLooseDate(periodM[2]!) : null,
        is_test_phase: /test\s+phase/i.test(fullText),
    };
}

export function makePageLookup(pages: string[]): { joined: string; pageOf: (offset: number) => number } {
    const boundaries: number[] = [];
    let joined = '';
    for (const p of pages) {
        boundaries.push(joined.length);
        joined += p + '\n';
    }
    const pageOf = (offset: number): number => {
        let page = 1;
        for (let i = 0; i < boundaries.length; i++) {
            if (offset >= boundaries[i]!) page = i + 1;
            else break;
        }
        return page;
    };
    return { joined, pageOf };
}

const KPI_TYPE_PATTERNS: Array<{ pattern: RegExp; type: KpiType }> = [
    { pattern: /reduce|decrease|lower|minimize|eliminate|avoid|prevent|absenteeism|overtime|waste/i, type: 'TYPE_2_LESS_MEANS_MORE' },
    { pattern: /zero\s+\w*\s*(incidents|defects|errors|accidents)|no\s+(incidents|defects|errors|accidents)/i, type: 'TYPE_3_LESS_OR_NOTHING' },
    { pattern: /compliance|certification|approval|complete|audit|closure/i, type: 'TYPE_4_ALL_OR_NOTHING' },
    { pattern: /incident|violation|accident|injury|safety/i, type: 'TYPE_5_NEGATIVE_SCORING' },
    { pattern: /satisfaction|engagement|rating|feedback|nps|csat/i, type: 'TYPE_8_RATING_SCALE' },
    { pattern: /increase|improve|grow|achieve|maximize|deliver|maintain|ensure|utili[sz]ation/i, type: 'TYPE_1_HIGHER_BETTER' },
];

function leadClause(objective: string): string {
    const breakAt = objective.search(/[.!]\s+(?=[A-Z])/);
    return breakAt === -1 ? objective : objective.slice(0, breakAt + 1);
}

export function inferKpiTypeFromObjective(objective: string): KpiType {
    const clause = leadClause(objective);
    for (const { pattern, type } of KPI_TYPE_PATTERNS) {
        if (pattern.test(clause)) return type;
    }
    return 'UNKNOWN';
}

const KPI_ANCHOR_RE = /Entire Cycle Type\s*(\d+)\s+(\d+(?:\.\d+)?)%\s*Complete/gi;
const PERSPECTIVE_RE = /Weight of Perspective:\s*([\d.]+)\s*([A-Za-z][A-Za-z &/]*?)(?=\n|$)/gi;

function numberAfterLabel(text: string, label: RegExp, from: number): { value: number; end: number } | null {
    const slice = text.slice(from);
    const labelM = label.exec(slice);
    if (!labelM) return null;
    label.lastIndex = 0;
    const afterLabel = from + labelM.index + labelM[0].length;
    const numM = /\s*(\d+(?:\.\d+)?)/.exec(text.slice(afterLabel, afterLabel + 40));
    if (!numM) return null;
    return { value: parseFloat(numM[1]!), end: afterLabel + (numM.index ?? 0) + numM[0].length };
}

function twoNumbersAfterLabel(text: string, label: RegExp, from: number): { values: [number, number]; end: number } | null {
    const slice = text.slice(from);
    const labelM = label.exec(slice);
    if (!labelM) return null;
    label.lastIndex = 0;
    const afterLabel = from + labelM.index + labelM[0].length;
    const window = text.slice(afterLabel, afterLabel + 80);
    const numsM = /\s*(\d+(?:\.\d+)?)\s*\n?\s*(\d+(?:\.\d+)?)/.exec(window);
    if (!numsM) return null;
    return {
        values: [parseFloat(numsM[1]!), parseFloat(numsM[2]!)],
        end: afterLabel + (numsM.index ?? 0) + numsM[0].length,
    };
}

const PER_KPI_COMMENT_RE = /^\s*(\d+)\s*COMMENT\(S\)\s*FOR\s+[A-Za-z\s]+?\n/;

function stripLeadingPerKpiComments(text: string): string {
    const m = PER_KPI_COMMENT_RE.exec(text);
    if (!m) return text;
    const count = parseInt(m[1]!, 10);
    const rest = text.slice(m.index + m[0].length);
    const lines = rest.split('\n');
    return lines.slice(Math.max(0, count) * 3).join('\n');
}

export function extractPerspectivesAndKpis(
    joined: string,
    pageOf: (offset: number) => number,
): { perspectives: SeamlessHrPerspectiveRaw[]; kpis: SeamlessHrKpiRaw[] } {
    const perspectiveHits: Array<{ name: string; weight: number; start: number; end: number }> = [];
    let pm: RegExpExecArray | null;
    const perspectiveRe = new RegExp(PERSPECTIVE_RE);
    while ((pm = perspectiveRe.exec(joined)) !== null) {
        if (pm[2] && cleanValue(pm[2]).length > 0) {
            perspectiveHits.push({
                weight: parseFloat(pm[1]!),
                name: cleanValue(pm[2]!),
                start: pm.index,
                end: pm.index + pm[0].length,
            });
        }
    }

    const markdownPerspectiveRe = /##\s*([A-Za-z][A-Za-z &/]*?)\s*\n\s*Weight of Perspective:\s*([\d.]+)/gi;
    let mpm: RegExpExecArray | null;
    while ((mpm = markdownPerspectiveRe.exec(joined)) !== null) {
        perspectiveHits.push({
            weight: parseFloat(mpm[2]!),
            name: cleanValue(mpm[1]!),
            start: mpm.index,
            end: mpm.index + mpm[0].length,
        });
    }

    perspectiveHits.sort((a, b) => a.start - b.start);

    const perspectives: SeamlessHrPerspectiveRaw[] = perspectiveHits.map((h) => ({
        name: h.name,
        weight: h.weight,
        source_page: pageOf(h.start),
    }));

    const anchors: Array<{ start: number; end: number; cycleType: number; completion: number }> = [];
    const anchorRe = new RegExp(KPI_ANCHOR_RE);
    let am: RegExpExecArray | null;
    while ((am = anchorRe.exec(joined)) !== null) {
        anchors.push({
            start: am.index,
            end: am.index + am[0].length,
            cycleType: parseInt(am[1]!, 10),
            completion: parseFloat(am[2]!),
        });
    }

    const kpis: SeamlessHrKpiRaw[] = [];
    let cursor = 0;

    for (let i = 0; i < anchors.length; i++) {
        const anchor = anchors[i]!;

        const perspectiveBetween = perspectiveHits.find((p) => p.start >= cursor && p.start < anchor.start);
        const objectiveStart = perspectiveBetween ? perspectiveBetween.end : cursor;
        const objective = cleanValue(
            stripLeadingPerKpiComments(joined.slice(objectiveStart, anchor.start).replace(FOOTER_RE, '')),
        );

        const currentPerspective = perspectiveHits
            .filter((p) => p.start <= anchor.start)
            .sort((a, b) => b.start - a.start)[0]?.name ?? null;

        let pos = anchor.end;
        const target = numberAfterLabel(joined, /Target/i, pos);
        if (target) pos = target.end;
        const actual = numberAfterLabel(joined, /Actual(?!\s*Score)/i, pos);
        if (actual) pos = actual.end;
        const actualScore = numberAfterLabel(joined, /Actual Score/i, pos);
        if (actualScore) pos = actualScore.end;
        const weight = numberAfterLabel(joined, /Weight(?!ed)/i, pos);
        if (weight) pos = weight.end;
        const weightedScore = numberAfterLabel(joined, /Weighted Score/i, pos);
        if (weightedScore) pos = weightedScore.end;
        const finalScore = numberAfterLabel(joined, /Final Score/i, pos);
        if (finalScore) pos = finalScore.end;

        let reviewer_target: number | null = null;
        let reviewer_actual: number | null = null;
        let employee_target: number | null = null;
        let employee_actual: number | null = null;

        const inlineRevEmpM = /Reviewer\s+Target\s+([\d,.]+)\s+Actual\s+([\d,.]+)\s+Employee\s+Target\s+([\d,.]+)\s+Actual\s+([\d,.]+)/i.exec(joined.slice(pos, pos + 250));
        if (inlineRevEmpM) {
            reviewer_target = parseFloat(inlineRevEmpM[1]!);
            reviewer_actual = parseFloat(inlineRevEmpM[2]!);
            employee_target = parseFloat(inlineRevEmpM[3]!);
            employee_actual = parseFloat(inlineRevEmpM[4]!);
            pos += inlineRevEmpM.index + inlineRevEmpM[0].length;
        } else {
            const reviewerEmployeeTarget = twoNumbersAfterLabel(joined, /Target/i, pos);
            if (reviewerEmployeeTarget) pos = reviewerEmployeeTarget.end;
            const reviewerEmployeeActual = twoNumbersAfterLabel(joined, /Actual(?!\s*Score)/i, pos);
            if (reviewerEmployeeActual) pos = reviewerEmployeeActual.end;

            reviewer_target = reviewerEmployeeTarget?.values[0] ?? null;
            employee_target = reviewerEmployeeTarget?.values[1] ?? null;
            reviewer_actual = reviewerEmployeeActual?.values[0] ?? null;
            employee_actual = reviewerEmployeeActual?.values[1] ?? null;
        }

        const storedType = SOURCE_TYPE_CODE_MAP[anchor.cycleType] ?? null;
        const inferredType = inferKpiTypeFromObjective(objective);

        kpis.push({
            code: `KPI-${String(i + 1).padStart(2, '0')}`,
            perspective: currentPerspective,
            objective,
            entire_cycle_type: anchor.cycleType,
            completion_percent: anchor.completion,
            target: target?.value ?? null,
            actual: actual?.value ?? null,
            actual_score: actualScore?.value ?? null,
            weight: weight?.value ?? null,
            weighted_score: weightedScore?.value ?? null,
            final_score_from_pdf: finalScore?.value ?? null,
            reviewer_target,
            reviewer_actual,
            employee_target,
            employee_actual,
            self_vs_supervisor_delta:
                reviewer_actual !== null && employee_actual !== null ? employee_actual - reviewer_actual : null,
            source_page: pageOf(anchor.start),
            kpi_type_from_pdf: storedType,
            kpi_type_inferred: inferredType,
            kpi_type: storedType ?? inferredType,
            kpi_type_divergence: storedType !== null && inferredType !== 'UNKNOWN' && storedType !== inferredType,
        });

        cursor = pos;
    }

    return { perspectives, kpis };
}

const COMMENT_HEADER_RE =
    /(\d{1,2}\w{0,2}\s+[A-Za-z]+,?\s*\d{4}\.\s*\d{1,2}:\d{2}\s*[AP]M)\s*([A-Z][A-Za-z.' -]+?)\s*\(([^)]+)\)/g;

export function extractComments(joined: string): SeamlessHrComment[] {
    const commentsSectionM = /COMMENT\(S\)([\s\S]*?)SIGNATURES/i.exec(joined);
    if (!commentsSectionM) return [];
    const section = commentsSectionM[1]!;

    const headers: Array<{ timestamp: string; name: string; role: string; start: number; end: number }> = [];
    const re = new RegExp(COMMENT_HEADER_RE);
    let m: RegExpExecArray | null;
    while ((m = re.exec(section)) !== null) {
        headers.push({
            timestamp: m[1]!,
            name: cleanValue(m[2]!),
            role: cleanValue(m[3]!),
            start: m.index,
            end: m.index + m[0].length,
        });
    }

    return headers.map((h, i) => {
        const sliceEnd = headers[i + 1]?.start ?? section.length;
        const bodyLines = section.slice(h.end, sliceEnd).split('\n').map(cleanValue).filter((l) => l.length > 0);
        return {
            commented_at: parseLooseTimestamp(h.timestamp),
            author_name: h.name,
            author_role: h.role,
            department: bodyLines[0] ?? null,
            text: bodyLines[1] ?? null,
        };
    });
}

export function extractRecommendations(joined: string): { line_manager: string | null; arc: string | null } {
    const lmM = /Line Manager\s+([A-Za-z][A-Za-z ]*)/i.exec(joined);
    const arcM = /ARC\s*\(Scribe\)\s+([A-Za-z][A-Za-z ]*)/i.exec(joined);
    return {
        line_manager: lmM ? cleanValue(lmM[1]!) : null,
        arc: arcM ? cleanValue(arcM[1]!) : null,
    };
}

export function extractSignaturesFromJoined(joined: string): {
    reviewer: SeamlessHrSignatory | null;
    counter_signer: SeamlessHrSignatory | null;
    arc: SeamlessHrSignatory | null;
} {
    const sigM = /SIGNATURES([\s\S]*)$/i.exec(joined);
    if (!sigM) return { reviewer: null, counter_signer: null, arc: null };
    const block = sigM[1]!;

    const roleBlockRe =
        /(Reviewer|Counter Signing|ARC)\s*\n\s*([A-Z][A-Za-z.' -]+?)\s*\n\s*([A-Za-z0-9 &/.,-]+?)\s*\n\s*(\d{1,2}\w{0,2}\s+[A-Za-z]+,?\s*\d{4}\.\s*\d{1,2}:\d{2}\s*[AP]M)/g;

    const result: Record<string, SeamlessHrSignatory> = {};
    let m: RegExpExecArray | null;
    const re = new RegExp(roleBlockRe);
    while ((m = re.exec(block)) !== null) {
        const role = m[1]!;
        result[role] = {
            name: cleanValue(m[2]!),
            department: cleanValue(m[3]!) || null,
            signed_at: parseLooseTimestamp(m[4]!),
        };
    }

    return {
        reviewer: result['Reviewer'] ?? null,
        counter_signer: result['Counter Signing'] ?? null,
        arc: result['ARC'] ?? null,
    };
}

export function parseSeamlessHrMultiPage(pages: string[]): SeamlessHrParsedAppraisal | null {
    if (pages.length === 0) return null;

    const cleanedPages = pages.map(stripBoilerplate);
    const { joined, pageOf } = makePageLookup(cleanedPages);

    const cover = extractCoverFields(cleanedPages[0]!);
    if (!cover.employee_name) return null;

    const period = extractPeriodFields(joined);
    const { perspectives, kpis } = extractPerspectivesAndKpis(joined, pageOf);
    const comments = extractComments(joined);
    const signatures = extractSignaturesFromJoined(joined);
    const recommendations = extractRecommendations(joined);

    return {
        cover,
        cycle_label: period.cycle_label,
        cycle_period_start: period.cycle_period_start,
        cycle_period_end: period.cycle_period_end,
        review_period_start: period.review_period_start,
        review_period_end: period.review_period_end,
        is_test_phase: period.is_test_phase,
        perspectives,
        kpis,
        comments,
        reviewer: signatures.reviewer,
        counter_signer: signatures.counter_signer,
        arc: signatures.arc,
        line_manager_recommendation: recommendations.line_manager,
        arc_recommendation: recommendations.arc,
    };
}
