import test, { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { parseSeamlessHrPdf } from '../../src/lib/parse/index.js';
import { evaluateARIG } from '../../src/lib/arig/evaluate.js';
import { validateNormalizedAppraisal } from '../../src/lib/schema/normalizedAppraisal.js';
import { HrMasterClient } from '../../src/lib/parse/hrMasterLookup.js';

describe('PHASE 5 — E2E Parser & ARIG Acceptance Flow', () => {
    const mockHrMaster: HrMasterClient = {
        async findByName(name: string) {
            if (name.toLowerCase().includes('julius')) {
                return [{ id: 'EMP-JD-001', name: 'Julius Danquah', department: 'HR & Corp. Comms.' }];
            }
            if (name.toLowerCase().includes('martha')) {
                return [{ id: 'EMP-MA-002', name: 'Martha Asare', department: 'Operations' }];
            }
            return [];
        },
    };

    it('E2E Julius Danquah: parses, validates schema, evaluates ARIG & flags segregation', async () => {
        const juliusDoc = `
Royal Crown Packaging Company Limited
Generated by SeamlessHR.com
Employee Name: Julius Danquah
APPRAISAL PERIOD: 1st January, 2026 - 31st May, 2026

## Financial
Weight of Perspective: 20

Reduce available overtime and absenteeism trends
Entire Cycle Type 1
50% Complete
Target 100 Actual 50 Actual Score 50
Weight 10 Weighted Score 5 Final Score 5
Reviewer Target 100 Actual 50 Employee Target 100 Actual 100
COMMENT(S) FOR KPI
Payroll accuracy: Poor attention to detail leading to poor validation and error correction during the pay cycle.
Sally Osei-Boateng
HR & Corp. Comms.
9th June, 2026. 12:48 PM

--- PAGE 2 ---
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

--- PAGE 3 ---
SIGNATURES
Reviewer
Sally Osei-Boateng
HR & Corp. Comms.
9th June, 2026. 1:13 PM
ARC
Sally Osei-Boateng
HR & Corp. Comms.
16th June, 2026. 9:00 AM
        `;

        const parseResult = await parseSeamlessHrPdf({
            buffer: juliusDoc,
            filename: 'julius_danquah.pdf',
            orgId: 'rcpl',
            hrMaster: mockHrMaster,
        });

        assert.equal(parseResult.success, true);
        const record = parseResult.record!;
        assert.ok(record);

        // Schema validation
        const val = validateNormalizedAppraisal(record);
        assert.equal(val.valid, true, `Validation errors: ${JSON.stringify(val.errors)}`);

        // Check artifact page detection
        const artifactWarn = record.warnings.find(w => w.code === 'WARN_ARTIFACT_PAGE');
        assert.ok(artifactWarn, 'Artifact page must be flagged and skipped');

        // Check KPI type divergence
        const divWarn = record.warnings.find(w => w.code === 'KPI_TYPE_DIVERGENCE');
        assert.ok(divWarn, 'KPI type divergence should be flagged when PDF is Type 1 and inferred is LESS_MEANS_MORE');

        // ARIG evaluation
        const arig = evaluateARIG(record, {
            org_id: 'rcpl',
            enabled_kpi_types: ['TYPE_1_HIGHER_BETTER', 'TYPE_2_LESS_MEANS_MORE'],
        });

        // Reviewer == ARC triggers Rule 24 Hard Lock
        const r24 = arig.responses.find(r => r.rule_code === 'SIGNATORY_SEGREGATION');
        assert.equal(r24?.passed, false);
        assert.equal(arig.hard_locked, true);
    });
});
