import test, { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { fingerprint } from '../../src/lib/parse/fingerprint.js';
import { classifyPage } from '../../src/lib/parse/pageClassify.js';
import { isArtifact, checkArtifact } from '../../src/lib/parse/artifactDetect.js';
import { inferKpiType } from '../../src/lib/parse/inferKpiType.js';
import { normalizeNumber, normalizeTimestamp } from '../../src/lib/parse/normalize.js';
import { lookupEmployee, HrMasterClient } from '../../src/lib/parse/hrMasterLookup.js';
import { parseSeamlessHrPdf } from '../../src/lib/parse/index.js';

describe('PHASE 4 — PARSER IMPLEMENTATION Acceptance Tests', () => {
    it('Fingerprint detection matches when ≥2 signals present', () => {
        const textWith2Signals = `
            Royal Crown Packaging Company Limited
            Entire Cycle Type 1
        `;
        const res = fingerprint(textWith2Signals);
        assert.equal(res.isSeamlessHR, true);
        assert.ok(res.signals.includes('company'));
        assert.ok(res.signals.includes('kpi_table'));

        const genericText = `Hello world, standard document without signals`;
        const negRes = fingerprint(genericText);
        assert.equal(negRes.isSeamlessHR, false);
    });

    it('Artifact detection identifies degenerate token grids (entropy < 0.1, tokens > 100)', () => {
        // Normal text
        const normalText = 'This is a genuine performance review page with diverse sentences and natural vocabulary distribution across the entire page.';
        assert.equal(isArtifact(normalText), false);

        // Degenerate page with repeated tokens
        const degenerateTokens = Array(200).fill('1').join(' ');
        const art = checkArtifact(degenerateTokens);
        assert.equal(art.isArtifact, true);
        assert.ok(art.entropy < 0.1);
    });

    it('Page classification correctly categorizes page types', () => {
        assert.equal(classifyPage('SIGNATURES\nReviewer\nSally', 1), 'SIGNATURE');
        assert.equal(classifyPage('4 Perspective 12 Objectives', 2), 'STRUCTURE');
        assert.equal(classifyPage('## Financial Perspective\nWeight of Perspective: 25', 3), 'PERSPECTIVE_START');
        assert.equal(classifyPage('Entire Cycle Type 1 100% Complete Target 100 Actual 100', 4), 'KPI_BLOCK');
    });

    it('KPI type inference correctly identifies types from objective text', () => {
        assert.equal(
            inferKpiType('Reduce overtime and absenteeism', 'Minimize labor costs'),
            'TYPE_2_LESS_MEANS_MORE'
        );
        assert.equal(
            inferKpiType('Zero safety incidents', 'Maintain zero injury threshold'),
            'TYPE_3_LESS_OR_NOTHING'
        );
        assert.equal(
            inferKpiType('Grow annual revenue', 'Maximize customer retention and revenue'),
            'TYPE_1_HIGHER_BETTER'
        );
        assert.equal(
            inferKpiType('Regulatory compliance closure', 'Ensure complete statutory compliance'),
            'TYPE_4_ALL_OR_NOTHING'
        );
    });

    it('Normalization handles messy numbers and timestamps', () => {
        assert.equal(normalizeNumber('1,250.50'), 1250.5);
        assert.equal(normalizeNumber('75%'), 75);
        assert.equal(normalizeNumber('GHS 500,000'), 500000);

        const iso = normalizeTimestamp('9th June, 2026. 1:13 PM');
        assert.equal(iso, '2026-06-09T13:13:00Z');
    });

    it('HR Master lookup resolves exact matches, multiple, and none', async () => {
        const mockHr: HrMasterClient = {
            async findByName(name: string) {
                if (name === 'Julius Danquah') {
                    return [{ id: 'EMP-001', name: 'Julius Danquah', department: 'HR' }];
                }
                if (name === 'John Smith') {
                    return [
                        { id: 'EMP-002', name: 'John Smith', department: 'Sales' },
                        { id: 'EMP-003', name: 'John Smith', department: 'Operations' },
                    ];
                }
                return [];
            },
        };

        const exact = await lookupEmployee('Julius Danquah', mockHr);
        assert.equal(exact.match, 'EXACT');
        assert.equal(exact.employee_id, 'EMP-001');

        const multi = await lookupEmployee('John Smith', mockHr);
        assert.equal(multi.match, 'MULTIPLE');
        assert.equal(multi.employee_id, null);

        const none = await lookupEmployee('Unknown Person', mockHr);
        assert.equal(none.match, 'NONE');
        assert.equal(none.employee_id, null);
    });

    it('End-to-end parseSeamlessHrPdf produces valid NormalizedAppraisal', async () => {
        const sampleText = `
Royal Crown Packaging Company Limited
Generated by SeamlessHR.com
Employee Name: Julius Danquah
APPRAISAL PERIOD: 1st January, 2026 - 31st May, 2026

## Financial
Weight of Perspective: 20

Reduce available overtime and absenteeism trends
Entire Cycle Type 1
50% Complete
Target 100 Actual 50 Actual Score 50
Weight 10 Weighted Score 5 Final Score 5
Reviewer Target 100 Actual 50 Employee Target 100 Actual 100
COMMENT(S) FOR KPI
Payroll accuracy: Poor attention to detail leading to poor validation and error correction during the pay cycle.
Sally Osei-Boateng
HR & Corp. Comms.
9th June, 2026. 12:48 PM

SIGNATURES
Reviewer
Sally Osei-Boateng
HR & Corp. Comms.
9th June, 2026. 1:13 PM
ARC
Dr. Kwaku Mensah
ARC Audit
16th June, 2026. 9:00 AM
        `;

        const mockHr: HrMasterClient = {
            async findByName() {
                return [{ id: 'EMP-JD-001', name: 'Julius Danquah', department: 'HR & Corp. Comms.' }];
            },
        };

        const result = await parseSeamlessHrPdf({
            buffer: sampleText,
            filename: 'Julius_Danquah.pdf',
            orgId: 'rcpl',
            hrMaster: mockHr,
        });

        assert.equal(result.success, true);
        assert.ok(result.record);
        assert.equal(result.record.employee.name, 'Julius Danquah');
        assert.equal(result.record.employee.employee_id, 'EMP-JD-001');
        assert.equal(result.record.kpis.length, 1);
        assert.equal(result.record.kpis[0]?.code, 'KPI-01');
        assert.equal(result.record.kpis[0]?.self_vs_supervisor_delta, 50);
        assert.equal(result.record.reviewer.name, 'Sally Osei-Boateng');
        assert.equal(result.record.arc?.name, 'Dr. Kwaku Mensah');
    });
});
